# Generated by Django 5.2.8 on 2025-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.BigIntegerField(max_length=16)),
                ('expiry', models.DateField()),
                ('cvs', models.IntegerField(max_length=3)),
            ],
        ),
    ]
