# Generated by Django 5.2.8 on 2025-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
